name: Test & Deploy to Koyeb

on: # configure this like you want idk really
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

env: # this is for deployment (we push the image to github container repo, then use that image for deployment)
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test: # this should work 100%, same as before
    runs-on: ubuntu-latest
    environment: onlineshop-env

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ vars.DEBUG }}" >> .env
        echo "MODE=LOCAL" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t onlineshopapp-web .

    - name: Run Docker container in background
      run: |
        docker run -d --name onlineshop_test \
          --env-file .env \
          -p 8000:8000 onlineshopapp-web

    - name: Run Django tests inside container
      run: |
        docker exec onlineshop_test python manage.py test --settings=onlineshop.test_settings

    - name: Stop and remove container
      run: |
        docker stop onlineshop_test
        docker rm onlineshop_test

  deploy: # This part I am not sure this will work, need to test.
    runs-on: ubuntu-latest
    environment: onlineshop-env # IMPORTANT - or secrets. will not work
    needs: build-test
    if: github.event_name == 'push' # configure this like you want idk really

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ toLowerCase(github.repository) }}:latest
          ghcr.io/${{ toLowerCase(github.repository) }}:${{ github.sha }}

    - name: Deploy to Koyeb
      uses: koyeb/action-git-deploy@v1
      with:
        token: ${{ secrets.KOYEB_TOKEN }}
        app_name: onlineshopapp
        service_name: web
        docker_image: ghcr.io/${{ toLowerCase(github.repository) }}:latest
        regions: fra
